# Generated by Django 4.1.7 on 2023-05-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('aspuname', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('cpwd', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=100)),
                ('phno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'aspirant_table',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('empuname', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('cpwd', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=100)),
                ('phno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'emp_table',
            },
        ),
        migrations.CreateModel(
            name='Jobprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspuname', models.CharField(max_length=50, unique=True)),
                ('skills', models.CharField(max_length=200)),
                ('sscresult', models.IntegerField(default=0)),
                ('interresult', models.IntegerField(default=0)),
                ('backlogs', models.IntegerField(default=0)),
                ('btechresult', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jobprofile_table',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('jrole', models.CharField(max_length=50, unique=True)),
                ('jdesc', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('On Campus', 'On Campus'), ('Off Campus', 'Off Campus')], max_length=10)),
                ('fromdate', models.DateField(default=None)),
                ('todate', models.DateField(default=None)),
                ('min_ssc', models.IntegerField(default=0)),
                ('min_inter', models.IntegerField(default=0)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('min_btech', models.IntegerField(default=0)),
                ('empuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.employer')),
            ],
            options={
                'db_table': 'job_table',
            },
        ),
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('appliedtime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('aspuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.aspirant')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.job')),
            ],
        ),
    ]
