# Generated by Django 4.1.7 on 2023-05-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applyjob',
            table='applyjob_table',
        ),
    ]
