# Generated by Django 4.1.7 on 2023-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_applyjob_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='empuname',
            field=models.CharField(max_length=50),
        ),
    ]
