# Generated by Django 4.1.7 on 2023-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_job_empuname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='aspuname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='jid',
            field=models.PositiveIntegerField(),
        ),
    ]
